"""add entity function

Revision ID: c1fe23250030
Revises: ad1c2c10a5d5
Create Date: 2018-06-08 12:37:44.264989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1fe23250030'
down_revision = 'ad1c2c10a5d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text(u'true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='dba'
    )
    op.create_table('database',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text(u'true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='dba'
    )
    op.create_table('environment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text(u'true'), nullable=False),
    sa.Column('domainprefix', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='dba'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dba'
    )
    op.create_index(op.f('ix_dba_user_email'), 'user', ['email'], unique=True, schema='dba')
    op.create_index(op.f('ix_dba_user_username'), 'user', ['username'], unique=True, schema='dba')
    op.create_table('cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text(u'true'), nullable=False),
    sa.Column('domainprefix', sa.String(), server_default='pgc', nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['dba.business.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='dba'
    )
    op.create_table('rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text(u'true'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['dba.business.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dba'
    )
    op.create_table('backup_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timecreated', sa.DateTime(), server_default=sa.text(u'NOW()'), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('scheduled', sa.String(length=12), nullable=False),
    sa.Column('state', sa.Boolean(), server_default=sa.text(u'false'), nullable=False),
    sa.Column('size', sa.Integer(), server_default=sa.text(u'0'), nullable=False),
    sa.Column('duration', sa.Integer(), server_default=sa.text(u'0'), nullable=False),
    sa.Column('info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['dba.cluster.id'], ),
    sa.ForeignKeyConstraint(['database_id'], ['dba.database.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dba'
    )
    op.create_table('deployment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text(u'true'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['dba.cluster.id'], ),
    sa.ForeignKeyConstraint(['database_id'], ['dba.database.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['dba.environment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='dba'
    )
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text(u'true'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['dba.cluster.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='dba'
    )
    op.create_table('recovery_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timecreated', sa.DateTime(), server_default=sa.text(u'NOW()'), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('scheduled', sa.String(length=12), nullable=False),
    sa.Column('state', sa.Boolean(), server_default=sa.text(u'true'), nullable=False),
    sa.Column('info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['dba.cluster.id'], ),
    sa.ForeignKeyConstraint(['database_id'], ['dba.database.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dba'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recovery_history', schema='dba')
    op.drop_table('node', schema='dba')
    op.drop_table('deployment', schema='dba')
    op.drop_table('backup_history', schema='dba')
    op.drop_table('rule', schema='dba')
    op.drop_table('cluster', schema='dba')
    op.drop_index(op.f('ix_dba_user_username'), table_name='user', schema='dba')
    op.drop_index(op.f('ix_dba_user_email'), table_name='user', schema='dba')
    op.drop_table('user', schema='dba')
    op.drop_table('environment', schema='dba')
    op.drop_table('database', schema='dba')
    op.drop_table('business', schema='dba')
    # ### end Alembic commands ###
